name: "Build and push Docker image to ACR"
 
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main 
 
#env:
#  VERSION: $(( $(cat version.txt) + 1 ))
  
jobs:
  
  build_push_supermario_docker_image:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
   
      - name: Calculate and Set Version Env
        run: |
          CURRENT_VERSION=$(cat version.txt)
          NEW_VERSION=$((CURRENT_VERSION + 1))
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
      
      - name: Login to Azure ACR
        uses: azure/docker-login@v2
        with:
          login-server: acrtest1-h5ezhaetamanf2as.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_TOKEN }}
 
      - name: Build and Push Docker Image
        run: |
          docker build -f dockerfile-for-mario-project-in-gitops-repo-main/Dockerfile -t acrtest1-h5ezhaetamanf2as.azurecr.io/azure-gitops:${{ env.VERSION }} .
          docker push acrtest1-h5ezhaetamanf2as.azurecr.io/azure-gitops:${{ env.VERSION }}

      