name: "Build and push Super Mario Docker image with dynamic tag to Docker Hub"
 
on:
  push:
    branches:
      - dockerimage 
 
env:
  VERSION: $(( $(cat version.txt) + 1 ))
  
jobs:
  
  build_push_supermario_docker_image:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
   
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Login to Azure ACR
        uses: azure/docker-login@v2
        with:
          login-server: acrtest1-h5ezhaetamanf2as.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_TOKEN }}
 
      - name: Build and Push Docker Image
        run: |
          docker build -f dockerfile-for-mario-project-in-gitops-repo-main/Dockerfile -t docker.io/rahulselvam/supermariogitopsproject:${{ env.VERSION }} .
          docker build -f dockerfile-for-mario-project-in-gitops-repo-main/Dockerfile -t docker.io/rahulselvam/supermariogitopsproject:${{ env.VERSION }} .
          docker push docker.io/rahulselvam/supermariogitopsproject:${{ env.VERSION }}
          docker push acrtest1-h5ezhaetamanf2as.azurecr.io/azure-gitops:${{ env.VERSION }}

      